# MongoDB
spring.mongodb.uri = mongodb+srv://StoneySpring688_db_admin:MmgPBMjSlCOLavsh@cluster0.i9q7wjv.mongodb.net/compraventas?retryWrites=true&w=majority

# Configuracion Api
server.port=8082

# Api Productos
api.productos.url = http://localhost:8080/api/productos/

# Api Usuarios
api.usuarios.url = http://localhost:8081/api/usuarios/
api.usuarios.auth.url = http://localhost:8081/api/auth/

# Adaptadores
productos.adaptador = retrofit
usuarios.adaptador = retrofit