# github oauth2
spring.security.oauth2.client.registration.github.clientId= Ov23liDl16imSLDg5EP3
spring.security.oauth2.client.registration.github.clientSecret= 4d402dc3a5f5ca4c5adfe8c54b60e4fdc0db7993

# netflix zuul
server.port = 8090
spring.application.name = pasarela
zuul.sensitiveHeaders=
zuul.routes.productos.path = /productos/**
zuul.routes.productos.url = http://localhost:8080/api/productos
zuul.routes.categorias.path = /categorias/**
zuul.routes.categorias.url = http://localhost:8080/api/categorias
zuul.routes.usuarios.path = /usuarios/**
zuul.routes.usuarios.url = http://localhost:8081/api/usuarios
zuul.routes.compraventas.path = /compraventas/**
zuul.routes.compraventas.url = http://localhost:8082/api/compraventas